### ISSUE TITLE
kealib 1.4.9 breaking import of GDAL

### ISSUE THREAD

**Issue by snowman2** [conda-forge/libgdal-feedstock#50] opened 2018-06-29 20:49 UTC
When I installed
```
gdal=2.2.4
libgdal=2.2.4
```
And attempted to import GDAL, 
```python
from osgeo import gdal
```
I would get the error:
```
    from osgeo import gdal
  File miniconda/envs/da/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "miniconda/envs/da/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "miniconda/envs/da/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "miniconda/envs/da/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libhdf5_cpp.so.102: cannot open shared object file: No such file or directory
```
I luckily had a previous working environment and tracked down the change to be `kealib`.

When I downgraded to `kealib=1.4.7` it worked.

**Comment by ocefpaf** [comment] 2018-06-29 20:56
I'm closing as a duplicate of https://github.com/conda-forge/gdal-feedstock/issues/209 (just to make it easier to track in one place).

Things should be OK as soon as I finish to rebuild the stack with `hdf 1.10.2`. (But it will take a while...)

**Closed as completed by ocefpaf** 2018-06-29 20:56 UTC
